version: '3'

services:
  app:
     image: f1-seaons-dev
     build: .
     ports:
       - 3000:3000
     volumes:
        - ./pages:/app/pages
        - ./public:/app/public
        - ./styles:/app/styles